### ISSUE TITLE
50系问题，我是从#443的issue过来的，但是重装CUDA和修改faster_whisper.py都没办法解决

### ISSUE THREAD

**Issue by Demorain123** [philpw99/VideoCaptioner#44]
### 问题描述 | Problem Description

然后我试了下大佬做的版本，把设置里的5000系的那个选项打开了，然后还是出现RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED这个问题。。。。离谱了，我是5080笔记本，难不成这个跟显卡驱动有关系？不过我这个显卡驱动还是出厂驱动，不可能有问题吧我去

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/db89ffa9-f1b2-4d86-98f5-7845886b231a" />

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：07 May 2025 16:50:47
开始转换音频
转换为音频执行命令: ffmpeg -i D:\XXX_Export_Here\6 May, 10.aac -map 0:a:0 -ac 1 -acodec pcm_s16le -ar 16000 -af aresample=async=1 -y D:\VideoCaptionerV1.2.0_3.6.8\_internal\work-dir\6 May, 10-ee5a06be\Audio_6 May, 10.wav
Stream mapping:
Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'D:\VideoCaptionerV1.2.0_3.6.8\_internal\work-dir\6 May, 10-ee5a06be\Audio_6 May, 10.wav':
Metadata:
ISFT            : Lavf60.16.100
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Metadata:
encoder         : Lavc60.31.102 pcm_s16le
size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A
size=    9984kB time=00:05:23.75 bitrate= 252.6kbits/s speed= 647x
size=   19456kB time=00:10:23.08 bitrate= 255.8kbits/s speed= 623x
size=   29440kB time=00:15:45.47 bitrate= 255.1kbits/s speed= 630x
size=   39936kB time=00:21:23.83 bitrate= 254.8kbits/s speed= 642x
size=   50688kB time=00:27:02.91 bitrate= 255.9kbits/s speed= 649x
size=   61184kB time=00:32:39.40 bitrate= 255.8kbits/s speed= 653x
size=   71680kB time=00:38:17.04 bitrate= 255.6kbits/s speed= 656x
size=   81408kB time=00:43:31.96 bitrate= 255.3kbits/s speed= 653x
[out#0/wav @ 000001a8305fe400] video:0kB audio:84539kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000090%
size=   84539kB time=00:45:05.23 bitrate= 256.0kbits/s speed= 654x
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl.exe -l en -m large-v2 --print_progress --model_dir D:\VideoCaptionerV1.2.0_3.6.8\_internal\AppData\models C:\Users\Mi\AppData\Local\Temp\bk_asr\tmpv7u8wq_h\audio.wav -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 1 --repetition_penalty 1.00 --beep_off
Standalone Faster-Whisper-XXL r245.4 running on: CUDA
Starting to process: C:\Users\Mi\AppData\Local\Temp\bk_asr\tmpv7u8wq_h\audio.wav
Starting sequential faster-whisper inference.
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2324, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2191, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-20400:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-05-07 16:51:04 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-05-07 16:51:04 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "app\core\thread\transcript_thread.py", line 213, in run
  File "app\core\bk_asr\BaseASR.py", line 73, in run
  File "app\core\bk_asr\FasterWhisperASR.py", line 255, in _run
RuntimeError
```

**Comment by Demorain123** [comment]
没问题了。。。。我去下载“Faster-Whisper-XXL_r245.4_windows.7z”，解压然后替换掉对应的目录就好了，非常之神奇。。。。。。

https://github.com/Purfview/whisper-standalone-win/releases

**Comment by philpw99** [comment]
谢谢你的反馈！这问题还是存在的，很奇怪明明你都设定了5000系列的补丁，为何fasterwhisperxxl 的命令行没有出现那个应该有的参数？这点我还是要回去查一查，看看怎么一回事。
还有，原来R245.4修改好了这个bug，这倒是不错的发现。

原来是逻辑有一点错误，修改了一下，看看行不行：
https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.6.9
